import React, { Component } from 'react';

// Styling the application
import { Layout } from "./components/layouts/Layout";
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom';
import PageLayout from './components/layouts/Page';
import ZeroChainFooter from './components/footer';
import ZeroChainHeader from './components/header';
import HomeScreen from './routes/HomeScreen';
import './App.css';
import { Table } from 'reactstrap';

// 0chain dStorage Metadata generated by the client
import { ZBOX_METADATA } from './config';

class App extends Component {

  constructor(props) {
    super(props);

    this.state = {
      documentHash: ZBOX_METADATA.documentHash,
      authTicket: ZBOX_METADATA.authTicket,
      lookupHash: ZBOX_METADATA.lookupHash,
      ethAddress: '',
      blockNumber: '',
      transactionHash: '',
      gasUsed: '',
      txReceipt: ''
    };
  }

  render() {
    return (
      <React.Fragment>
        <Router>
        <Layout>
          <div className="text-center">
          <header className="0Chain-header">
              <ZeroChainHeader />
            </header>
            <Switch>
              <Route
                exact
                path="/"
                render={props => {
                  return <PageLayout content={<HomeScreen {...props} />} />;
                }}
              />
            </Switch>
            <br />
            <Table bordered responsive>
              <thead>
                <tr>
                  <th>Ethereum Transaction Details</th>
                  <th>Values</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Document Hash</td>
                  <td>{this.state.documentHash}</td>
                </tr>
                <tr>
                  <td>Lookup Hash</td>
                  <td>{this.state.lookupHash}</td>
                </tr>
                <tr>
                  <td>Allocation ID</td>
                  <td>{this.state.allocationId}</td>
                </tr>
                <tr>
                  <td>Ethereum Contract Address</td>
                  <td>{this.state.ethAddress}</td>
                </tr>
                <tr>
                  <td>Transaction Hash </td>
                  <td>{this.state.transactionHash}</td>
                </tr>
                <tr>
                  <td>Block Number </td>
                  <td>{this.state.blockNumber}</td>
                </tr>
                <tr>
                  <td>Gas Used</td>
                  <td>{this.state.gasUsed}</td>
                </tr>
              </tbody>
            </Table>
          </div>
        </Layout>
        <footer className="0Chain-footer">
              <ZeroChainFooter />
        </footer>
        </Router>
      </React.Fragment>
    );
  }
}
export default App;